package com.shiki.domain.dao;

import com.shiki.domain.dto.SPerms;
import com.shiki.domain.dto.SPermsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SPermsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_perms
     *
     * @mbggenerated Thu Jun 27 13:37:11 CST 2019
     */
    int countByExample(SPermsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_perms
     *
     * @mbggenerated Thu Jun 27 13:37:11 CST 2019
     */
    int deleteByExample(SPermsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_perms
     *
     * @mbggenerated Thu Jun 27 13:37:11 CST 2019
     */
    int deleteByPrimaryKey(Long permsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_perms
     *
     * @mbggenerated Thu Jun 27 13:37:11 CST 2019
     */
    int insert(SPerms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_perms
     *
     * @mbggenerated Thu Jun 27 13:37:11 CST 2019
     */
    int insertSelective(SPerms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_perms
     *
     * @mbggenerated Thu Jun 27 13:37:11 CST 2019
     */
    List<SPerms> selectByExample(SPermsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_perms
     *
     * @mbggenerated Thu Jun 27 13:37:11 CST 2019
     */
    SPerms selectByPrimaryKey(Long permsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_perms
     *
     * @mbggenerated Thu Jun 27 13:37:11 CST 2019
     */
    int updateByExampleSelective(@Param("record") SPerms record, @Param("example") SPermsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_perms
     *
     * @mbggenerated Thu Jun 27 13:37:11 CST 2019
     */
    int updateByExample(@Param("record") SPerms record, @Param("example") SPermsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_perms
     *
     * @mbggenerated Thu Jun 27 13:37:11 CST 2019
     */
    int updateByPrimaryKeySelective(SPerms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_perms
     *
     * @mbggenerated Thu Jun 27 13:37:11 CST 2019
     */
    int updateByPrimaryKey(SPerms record);
}