package com.shiki.domain.dao;

import com.shiki.domain.dto.SRole;
import com.shiki.domain.dto.SRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbggenerated Thu Jun 27 16:12:35 CST 2019
     */
    int countByExample(SRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbggenerated Thu Jun 27 16:12:35 CST 2019
     */
    int deleteByExample(SRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbggenerated Thu Jun 27 16:12:35 CST 2019
     */
    int deleteByPrimaryKey(Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbggenerated Thu Jun 27 16:12:35 CST 2019
     */
    int insert(SRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbggenerated Thu Jun 27 16:12:35 CST 2019
     */
    int insertSelective(SRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbggenerated Thu Jun 27 16:12:35 CST 2019
     */
    List<SRole> selectByExample(SRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbggenerated Thu Jun 27 16:12:35 CST 2019
     */
    SRole selectByPrimaryKey(Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbggenerated Thu Jun 27 16:12:35 CST 2019
     */
    int updateByExampleSelective(@Param("record") SRole record, @Param("example") SRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbggenerated Thu Jun 27 16:12:35 CST 2019
     */
    int updateByExample(@Param("record") SRole record, @Param("example") SRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbggenerated Thu Jun 27 16:12:35 CST 2019
     */
    int updateByPrimaryKeySelective(SRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbggenerated Thu Jun 27 16:12:35 CST 2019
     */
    int updateByPrimaryKey(SRole record);
}