package com.shiki.domain.dto;

import java.util.ArrayList;
import java.util.List;

public class SPermsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_perms
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_perms
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_perms
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_perms
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    public SPermsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_perms
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_perms
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_perms
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_perms
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_perms
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_perms
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_perms
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_perms
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_perms
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_perms
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table s_perms
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPermsIdIsNull() {
            addCriterion("perms_id is null");
            return (Criteria) this;
        }

        public Criteria andPermsIdIsNotNull() {
            addCriterion("perms_id is not null");
            return (Criteria) this;
        }

        public Criteria andPermsIdEqualTo(Integer value) {
            addCriterion("perms_id =", value, "permsId");
            return (Criteria) this;
        }

        public Criteria andPermsIdNotEqualTo(Integer value) {
            addCriterion("perms_id <>", value, "permsId");
            return (Criteria) this;
        }

        public Criteria andPermsIdGreaterThan(Integer value) {
            addCriterion("perms_id >", value, "permsId");
            return (Criteria) this;
        }

        public Criteria andPermsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("perms_id >=", value, "permsId");
            return (Criteria) this;
        }

        public Criteria andPermsIdLessThan(Integer value) {
            addCriterion("perms_id <", value, "permsId");
            return (Criteria) this;
        }

        public Criteria andPermsIdLessThanOrEqualTo(Integer value) {
            addCriterion("perms_id <=", value, "permsId");
            return (Criteria) this;
        }

        public Criteria andPermsIdIn(List<Integer> values) {
            addCriterion("perms_id in", values, "permsId");
            return (Criteria) this;
        }

        public Criteria andPermsIdNotIn(List<Integer> values) {
            addCriterion("perms_id not in", values, "permsId");
            return (Criteria) this;
        }

        public Criteria andPermsIdBetween(Integer value1, Integer value2) {
            addCriterion("perms_id between", value1, value2, "permsId");
            return (Criteria) this;
        }

        public Criteria andPermsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("perms_id not between", value1, value2, "permsId");
            return (Criteria) this;
        }

        public Criteria andPermsNameIsNull() {
            addCriterion("perms_name is null");
            return (Criteria) this;
        }

        public Criteria andPermsNameIsNotNull() {
            addCriterion("perms_name is not null");
            return (Criteria) this;
        }

        public Criteria andPermsNameEqualTo(String value) {
            addCriterion("perms_name =", value, "permsName");
            return (Criteria) this;
        }

        public Criteria andPermsNameNotEqualTo(String value) {
            addCriterion("perms_name <>", value, "permsName");
            return (Criteria) this;
        }

        public Criteria andPermsNameGreaterThan(String value) {
            addCriterion("perms_name >", value, "permsName");
            return (Criteria) this;
        }

        public Criteria andPermsNameGreaterThanOrEqualTo(String value) {
            addCriterion("perms_name >=", value, "permsName");
            return (Criteria) this;
        }

        public Criteria andPermsNameLessThan(String value) {
            addCriterion("perms_name <", value, "permsName");
            return (Criteria) this;
        }

        public Criteria andPermsNameLessThanOrEqualTo(String value) {
            addCriterion("perms_name <=", value, "permsName");
            return (Criteria) this;
        }

        public Criteria andPermsNameLike(String value) {
            addCriterion("perms_name like", value, "permsName");
            return (Criteria) this;
        }

        public Criteria andPermsNameNotLike(String value) {
            addCriterion("perms_name not like", value, "permsName");
            return (Criteria) this;
        }

        public Criteria andPermsNameIn(List<String> values) {
            addCriterion("perms_name in", values, "permsName");
            return (Criteria) this;
        }

        public Criteria andPermsNameNotIn(List<String> values) {
            addCriterion("perms_name not in", values, "permsName");
            return (Criteria) this;
        }

        public Criteria andPermsNameBetween(String value1, String value2) {
            addCriterion("perms_name between", value1, value2, "permsName");
            return (Criteria) this;
        }

        public Criteria andPermsNameNotBetween(String value1, String value2) {
            addCriterion("perms_name not between", value1, value2, "permsName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table s_perms
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 24 14:11:35 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table s_perms
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}