package com.shiki.domain.dto;

import java.io.Serializable;

public class SPerms implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_perms.perms_id
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    private Integer permsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_perms.perms_name
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    private String permsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_perms
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_perms.perms_id
     *
     * @return the value of s_perms.perms_id
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    public Integer getPermsId() {
        return permsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_perms.perms_id
     *
     * @param permsId the value for s_perms.perms_id
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    public void setPermsId(Integer permsId) {
        this.permsId = permsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_perms.perms_name
     *
     * @return the value of s_perms.perms_name
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    public String getPermsName() {
        return permsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_perms.perms_name
     *
     * @param permsName the value for s_perms.perms_name
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    public void setPermsName(String permsName) {
        this.permsName = permsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_perms
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", permsId=").append(permsId);
        sb.append(", permsName=").append(permsName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}