package com.shiki.domain.dto;

import java.io.Serializable;

public class SText implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_text.text_id
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    private Integer textId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_text.user_id
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_text.title
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_text.create_time
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_text.is_delete
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    private Boolean isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_text.text
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_text
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_text.text_id
     *
     * @return the value of s_text.text_id
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    public Integer getTextId() {
        return textId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_text.text_id
     *
     * @param textId the value for s_text.text_id
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    public void setTextId(Integer textId) {
        this.textId = textId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_text.user_id
     *
     * @return the value of s_text.user_id
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_text.user_id
     *
     * @param userId the value for s_text.user_id
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_text.title
     *
     * @return the value of s_text.title
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_text.title
     *
     * @param title the value for s_text.title
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_text.create_time
     *
     * @return the value of s_text.create_time
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_text.create_time
     *
     * @param createTime the value for s_text.create_time
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_text.is_delete
     *
     * @return the value of s_text.is_delete
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_text.is_delete
     *
     * @param isDelete the value for s_text.is_delete
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_text.text
     *
     * @return the value of s_text.text
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_text.text
     *
     * @param text the value for s_text.text
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_text
     *
     * @mbggenerated Mon Jun 24 14:11:35 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", textId=").append(textId);
        sb.append(", userId=").append(userId);
        sb.append(", title=").append(title);
        sb.append(", createTime=").append(createTime);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", text=").append(text);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}